### ISSUE TITLE
Something not quite right with model search

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJ#6]
When I search "SVC" the model with that name does not appear, despite the fact that it *does* appear when I click on "Classifiers".

![Screen Shot 2024-06-18 at 10 42 47 AM](https://github.com/JuliaAI/MLJ/assets/30517088/1251c536-7507-448f-85cd-beb6dd027480)

**Comment by ablaom** [comment]
Also, if I search "LIBSVM", nothing at all appears, but perhaps that's because I can only search over model names?

The truth is that the search bar on the [manual homepage](https://juliaai.github.io/MLJ.jl/dev/) is WAY more useful, as it searches over the entire manual, including every model docstring. I don't like the idea of presenting an inferior tool here, but I also don't like the idea of duplication. Any ideas?

**Comment by EssamWisam** [comment]
It's likely easy for me to extend it to include the whole string instead of just the model name. My idea was simply that model names are more or less universal.

> The truth is that the search bar on the [manual homepage](https://juliaai.github.io/MLJ.jl/dev/) is WAY more useful, as it searches over the entire manual, including every model docstring.

To me this creates more confusion. When I'm only looking for the SVM model but get references in other irrelevant pages in the documentation (e.g., just tried searching now and I see that as well as duplicate results in the search). I find it more organized and less confusing for different types of material (e.g., models and tutorials) to have different search engines. It's unlikely that I am interested in every page that mentions SVM.

This is irrelevant but I also don't like the default docs search because it sometimes lists results without mentioning the string where the term ocurred similar to Google so one has to click to find out if the context is what they were looking for or not.

> I don't like the idea of presenting an inferior tool here

Does it remain in that state in your view given the thoughts I have just shared and the fact that it's easy to extend it to search over the model name or source package (whole model string)? It's not straightforward for me to envision a user story where they are trynig to find a model by searching for a term in its docstring instead of the model name or package name.

> I also don't like the idea of duplication

Can view that this doesn't duplicate the functionality since it makes it easier to search for models by restricting the search space. It's also more accessible/comprehendible to business people compared to the search in the manual.

**Comment by ablaom** [comment]
> It's likely easy for me to extend it to include the whole string instead of just the model name. My idea was simply that model names are more or less universal.

I'm not sure I understand, but here would be the "minimum" behaviour I would be expecting (which is not implemented at present - see my very first example): I get hits whenever `contains(model_name, search_string)`. The model name "SVC" certainly contains the search string "SVC" but no result appears in the search. 

More useful would be hits for `contains(model_name, search_string) || contains(package_name, search_string)`. I think every "interface" package name contains the corresponding model-providing package name as a substring, so no need to search interface package names.

> To me this creates more confusion. 

Okay, but can we at least have a link for "Search entire documentation"?

**Comment by EssamWisam** [comment]
When I mentioned
> It's likely easy for me to extend it to include the whole string instead of just the model name. My idea was simply that model names are more or less universal.

I poorly used the term "the whole string" to refer to
<img width="1193" alt="image" src="https://github.com/JuliaAI/MLJ/assets/49572294/18e7c091-c9a3-4348-91fc-152730236aa5">
which is the same as you requested.

> Okay, but can we at least have a link for "Search entire documentation"?

Absolutely but two small caveats: I can't get a link for the search pop up in the manual and with this we will have to think of a new place to put the rotating recommendations (as `Search entire documentation` would best go below the search which was planned for the rotating recommenation).

**Comment by ablaom** [comment]
> Absolutely but two small caveats: I can't get a link for the search pop up in the manual and with this we will have to think of a new place to put the rotating recommendations (as Search entire documentation would best go below the search which was planned for the rotating recommenation).

Can "Search entire documentation" link appear *below* the search bar.

>  I can't get a link for the search pop up in the manual 

I think a link to the manual landing page would be fine for now.

**Comment by EssamWisam** [comment]
> Can "Search entire documentation" link appear below the search bar.

Yes, I'd say that's the right place for it but I still haven't thought about where to put the rotating recommendations in this case (in the other thread we mentioned below search bar also?)

**Comment by EssamWisam** [comment]
This is almost solved as demonstrated in the last call.

**Comment by EssamWisam** [comment]
<img width="1418" alt="image" src="https://github.com/JuliaAI/MLJ/assets/49572294/e9c67ed9-563c-4c57-ac95-56d4fa4f908d">

It was hard for me to put it somewhere else (tried top but wasn't cool) and double bottom wasn't good as well. What do you think about this? 

When you click there is simply takes you to the documentation (which can be improved if [this](https://github.com/JuliaDocs/Documenter.jl) ever gets resolved. Also rational for a reason: they only need to see it when the search results are not sufficient (and not necessarily even before starting the search).

**Comment by ablaom** [comment]
Very clever. Love it.
